### ISSUE TITLE
Add `InProgress` variant to `io::ErrorKind`

### ISSUE THREAD

**Issue by aviramha** [rust-lang/libs-team#92] opened 2022-08-29 16:02 UTC
# Proposal

Add `InProgress` variant to `io::ErrorKind` to support cases where OS error is `libc::EINPROGRESS`

## Problem statement

While working on API that relies on `io::last_os_error` I found out that `kind` field of `io::Error` is set to `Uncategorized` which means I can't "safely" use `.kind()` to check if it's a specific error, in our case `libc::EINPROGRESS`

## Motivation, use-cases

[Our code example that can be simplified given the addition](https://github.com/metalbear-co/mirrord/blob/6b3fc55f2ddda7dc0836d9eb20225efa1b490b44/mirrord-layer/src/socket/ops.rs#L239-L251).

## Links and related work

Sent a PR of the proposed change 
https://github.com/rust-lang/rust/pull/101155#pullrequestreview-1088931007

**Comment by aviramha** [comment] 2022-08-29 16:04
@thomcc brought up [in the PR ](https://github.com/rust-lang/rust/pull/101155#issuecomment-1230490766) that it's similar to `WouldBlock`. I do agree but my objective is to be aware when `EINPROGRESS` happened and that's Linux error codes quirks. To be honest I'm okay with matching `EINPROGRESS` to `WouldBlock` but it might be weird and intuitive for most people.

**Comment by thomcc** [comment] 2022-08-29 17:19
I don't think it makes sense for us to reflect all errno values in `ErrorKind` -- this is what [`raw_os_error`](https://doc.rust-lang.org/nightly/std/io/struct.Error.html#method.raw_os_error) is for, after all.

But, on the one hand, `WouldBlock` is quite specific -- it definitely implies that it maps to `EWOULDBLOCK`.

**Comment by aviramha** [comment] 2022-08-29 17:42
> I don't think it makes sense for us to reflect all errno values in `ErrorKind` -- this is what [`raw_os_error`](https://doc.rust-lang.org/nightly/std/io/struct.Error.html#method.raw_os_error) is for, after all.
> 
> 
> 
> But, on the one hand, `WouldBlock` is quite specific -- it definitely implies that it maps to `EWOULDBLOCK`.

I'm fine with that. I am not really synced with the general thought of best practice in this so really up to the maintainers 😊

**Comment by aviramha** [comment] 2022-09-17 12:21
Took @thomcc and changed the PR to use `WouldBlock` error instead of `InProgress`

**Comment by joshtriplett** [comment] 2023-05-17 13:02
Sounds like this got resolved without adding this variant.

We may, in the future, want to add such a variant for other purposes, but it sounds like we can close this ACP for now.

**Comment by joshtriplett** [comment] 2023-08-01 15:47
This seems to have gotten closed on the theory that `EINPROGRESS` could get mapped to `WouldBlock`, but as discussed on the PR and in today's libs-api meeting, that's not the right mapping. If we do provide a mapping for this, it should be to a separate `ErrorKind` variant.

**Comment by joshtriplett** [comment] 2023-08-01 15:48
We don't have a consensus in @rust-lang/libs-api to create an `ErrorKind` variant for this.

Leaving this open in the hopes that we reach a consensus to do so.

**Comment by aviramha** [comment] 2023-08-01 17:00
Thanks for discussing this.
I believe that `EINPROGRESS` is quite commonly used - it isn't a seldom error so if there's anything I can do to convince adding it - I'd love to push for it :)

**Comment by m-ou-se** [comment] 2023-08-15 13:22
Originally we thought it'd make sense to merge this with `ErrorKind::WouldBlock`, but then later it seemed clear that EAGAIN and EINPROGRESS should not be treated the same in most cases.

However, when we try to discuss this in the team meeting, we get stuck on not having a complete overview of how these errors occur and are handled in practice, especially on different platforms.

So, to move this forward, we'll need a bit more context to answer questions like: When does this error occur? How does one usually handle this error? Does it exist on non-unix platforms? If so, does it represent the exact same thing? Would adding this `ErrorKind` result in more or less platform-specific code in practice?

**Comment by aviramha** [comment] 2023-08-15 14:06
Thanks @m-ou-se - I will try to provide my findings.
Personally, I don't think that mapping `EINPROGRESS` to `WouldBlock` would make sense tbh (and that was my opinion since I created thie issue)

## When does it occur?

It occurs when you call a procedure which can take time to complete, and isn't blocking to completion - in sockets for example when the socket is set to not block, and you call `connect` it'd return immediately with the `EINPRGORESS`.

## How does one usually handle this error?

It's considered a non-error, it's a way of letting the caller know that the operation didn't fail but also didn't complete yet. We originally faced it because our code "errored" while getting this while it's not a "true" error. The handling is success - continue.

## Does it exist on non-unix platforms?

It exists on Windows and other POSIX-compliant systems, not sure about other?
The representation of `EINPRGORESS` across platforms is same, and in all isn't same as `EWOULDBLOCK` or `EAGAIN`.

## Would adding this `ErrorKind` result in more or less platform-specific code in practice?

Hard to say, but right now we're just accessing the raw os instead of using the variant, which what annoyed me to create this issue.

**Comment by joshtriplett** [comment] 2024-09-24 15:31
We discussed this once more in today's libs-api meeting, and confirmed that we want this to be a separate `ErrorKind` variant, `InProgress`.

The primary intended distinction here (various platform portability issues aside) is that `WouldBlock` means you should retry the operation when ready, and `InProgress` means you *shouldn't* retry the operation.

**Comment by aviramha** [comment] 2024-09-24 15:37
Woohoo! Great news. Is it okay if I send a PR?

**Closed** 2024-09-24 15:37 UTC
Labels: I-libs-api-nominated, T-libs-api, api-change-proposal

**Comment by joshtriplett** [comment] 2024-09-24 15:40
@aviramha Please do reopen, or make a new one, whichever is simpler for providing a PR that applies.

**Comment by aviramha** [comment] 2024-09-24 15:53
Done https://github.com/rust-lang/rust/pull/130789
