### ISSUE TITLE
Add `get_unchecked` to `Option` and `Result`

### ISSUE THREAD

**Issue by alion02** [rust-lang/libs-team#378] opened 2024-05-05 03:07 UTC
# Proposal

## Problem statement

Prompted by [this comment:](https://internals.rust-lang.org/t/expose-llvms-or-disjoint-instruction/20708/3)
> Similarly, you can already write:
> ```rs
> unsafe { a.checked_mul(b).unwrap_unchecked() }
> ```
> so it's strange to me that additional functions like `unchecked_mul` are being added to `u32` for this specific operation.

I began searching for concrete examples of situations where using `unwrap_unchecked` leads to bad codegen. I didn't have to search long.

The problem with `unwrap_unchecked` is that it's the programming equivalent of littering - with every unwrap we're sprinkling in a condition for LLVM to keep around, even though frequently what we *really* mean is "I know this is `Some`/`Ok`/`Err`, please give me the contents without checking the variant." In a perfect world, these conditions would just get ignored when irrelevant and cleanly DCE'd, but...

## Motivating examples or use cases

```rs
type NZ = core::num::NonZeroU32;
type U = u32;

#[no_mangle]
unsafe fn sum_unwrap(a: &[Option<NZ>; 16]) -> U {
    a.iter().map(|&v| v.unwrap_unchecked().get()).sum()
}
```
[godbolt](https://godbolt.org/z/41G6snWoz)

This innocuous snippet leads to staggeringly bad assembly - 80+ lines of LLVM IR and 30+ ARM instructions... to add together 16 numbers. For reference, a non-vectorized implementation would be 15 adds, 8 pair-loads, and a return. Autovectorized it's just 8 instructions.

## Solution sketch

Maybe we should just stop littering.

We can restore good codegen if we express the unwrap in a different way, without invoking `unreachable_unchecked`; for example, like this:
```rs
trait OptionExt {
    type T;
    unsafe fn get_unchecked(self) -> Self::T;
}

impl<T> OptionExt for Option<T> {
    type T = T;

    #[allow(invalid_value)]
    unsafe fn get_unchecked(self) -> T {
        match self {
            Some(v) => v,
            None => core::mem::MaybeUninit::uninit().assume_init(),
        }
    }
}
```
[godbolt](https://godbolt.org/z/WqfcT7Ys9)

Add the above method (and analogous methods on `Result`) to `core`.

### Change implementation of `unwrap_unchecked`
Idly browsing through uses of `unwrap_unchecked`, I notice that a significant portion (perhaps even majority!) of them probably don't care to keep their conditions around. Worth investigating with benchmarks.

Not convinced it's relevant, but clang does not generate an `assume` for an `std::optional` dereference. [godbolt](https://godbolt.org/z/zxdqMxex6)

Additionally, the "unchecked" wording sort of implies a lack of checks, which is... well, *ostensibly* true...

### Change current implementation *and* add new methods
Assuming `get_unchecked` is on average better than `unwrap_unchecked`, we might want to replace the functionality for current code and also keep providing the previous functionality for the cases where it is useful. Call it `unwrap_assume` or something.

### Do nothing
This can be implemented in user code just fine, as an extension method. The problem is discoverability - if you're reaching for `unwrap_unchecked`, you probably care about performance, and with `unwrap_unchecked` being the only `unchecked` method on `Option`/`Result` you might not think to search further, or consider what the method does under the hood (and whether that's something you want to happen).

### Improve LLVM
Presumably a long-term effort. I don't have the necessary knowledge to properly consider this alternative.

**Comment by Nilstrieb** [comment] 2024-05-05 05:04
this is just a duplicate of unwrap_unchecked, there's no value in having both

**Comment by workingjubilee** [comment] 2024-05-05 05:53
> Additionally, the "unchecked" wording sort of implies a lack of checks, which is... well, ostensibly true...

The documentation for `Option::unwrap_unchecked` says:
> Returns the contained [Some](https://doc.rust-lang.org/std/option/enum.Option.html#variant.Some) value, consuming the self value, without checking that the value is not [None](https://doc.rust-lang.org/std/option/enum.Option.html#variant.None).

So we do not promise the implementation of `Option::unwrap_unchecked` is specifically `None => unreachable_unchecked()`.

**Comment by kennytm** [comment] 2024-05-05 06:49
You'll get the same optimized ASM using safe functions alone

```rust
#[no_mangle]
fn sum_map_or(a: &[Option<NZ>; 16]) -> U {
    a.iter().map(|&v| v.map_or(0, NZ::get)).sum()
}
```

**Comment by pitaj** [comment] 2024-05-07 17:46
> `v.unwrap_or_zero()`

That's just `unwrap_or_default` right?

**Comment by dtolnay** [comment] 2024-05-19 02:34
Thank you for the ACP, discussion, godbolt links, and draft PRs for benchmarking!

We discussed this ACP in this week's standard library API team meeting. Those present were not convinced that having 2 unsafe `Option<T>`-&gt;`T` conversions, one using `intrinsics::unreachable()` and the other `MaybeUninit::uninit().assume_init()` or something else, was worth having at this time.

But instead we are open to whatever improvements can be made to LLVM, rustc, or the standard library to make the existing `unwrap_unchecked` lead to better code on average.

We didn't get a chance to evaluate `Option<NonZero<_>>::unwrap_or_zero` (https://github.com/rust-lang/libs-team/issues/378#issuecomment-2098921092, https://github.com/rust-lang/libs-team/issues/378#issuecomment-2099002444) as a team, but that would be a separate ACP. My personal opinion is that `option.map_or(0, NonZero::get)` is good enough for this, but it wouldn't surprise me if others on the team feel inversely.

**Closed by dtolnay** 2024-05-19 02:34 UTC
Labels: T-libs-api, api-change-proposal
